name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore AutoSwitchThemeW11/AutoSwitchThemeW11.csproj --runtime win-x64
    
    - name: Build
      run: dotnet build AutoSwitchThemeW11/AutoSwitchThemeW11.csproj --no-restore --configuration Release --runtime win-x64
    
    - name: Test
      run: dotnet test AutoSwitchThemeW11/AutoSwitchThemeW11.csproj --no-build --verbosity normal --configuration Release
    
    - name: Publish
      run: dotnet publish AutoSwitchThemeW11/AutoSwitchThemeW11.csproj --no-build --configuration Release --output ./publish/win-x64 --runtime win-x64 --self-contained true
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: ./publish/win-x64/
        retention-days: 30
